### ISSUE TITLE
`distribution` is not included on the type of BufferedMetricsLogger

### ISSUE THREAD

**Issue by stuckinaboot** [dbader/node-datadog-metrics#109]
It appears that `distribution` is not included on the type of BufferedMetricsLogger. Adding that would help promote type safety

**Comment by Mr0grog** [comment]
Are they missing types from `@types/datadog-metrics` (not maintained by the authors of this package), or are you experience issues with the built-in types that will be part of the next release in v0.11? (See #104.)

If your issue is with `@types/datadog-metrics`, please file an issue on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/datadog-metrics), since we don’t maintain those.

The code here *should* be including type annotations for `distribution`. If you are using the not-yet-released version, could you please let me know how you are installing the package and what errors you are seeing?

**Comment by Mr0grog** [comment]
We’ve now released v0.11.0 with built-in types, so I’m closing this.
