### ISSUE TITLE
Type mismatch issue when submitting metrics with tags.

### ISSUE THREAD

**Issue by jayshah123** [dbader/node-datadog-metrics#133]
I am seeing this warning/error when submitting metrics:
```
could not serialize Array<number> (TypeError: mismatch types '1731477130' and 'Array<number>')
could not serialize number (TypeError: unknown type 'number')
```
This seems to be coming from - https://github.com/DataDog/datadog-api-client-typescript/blob/b56725b4ac6154403442ed02fe511c27a960d000/packages/datadog-api-client-v1/models/ObjectSerializer.ts#L2494.

Debugger screenshot (breakpoint on above error message):
<img width="660" alt="Screenshot 2024-11-13 at 11 27 38 AM" src="https://github.com/user-attachments/assets/35c67c51-8d35-466c-832e-b0cbda6fb9d7">

Is there any workaround I can try?
If this is expected behaviour, is there a way to supress these messages? I am using this lib to send metrics from a cli, where this stdout/stderr output affects the experience.

**Comment by jayshah123** [comment]
Nevermind, this was additional logging, because I was running my CLI with `DEBUG=*` and hence datadog api client was logging warnings.

**Comment by Mr0grog** [comment]
Ugh, that definitely is a confusing error! It looks like we are doing something wrong that is getting automatically fixed for us, so I took a deeper look. It turns out that the Datadog client logs this error even when everything is _exactly_ correct. 😫 

If you are more curious on the details, it’s trying to serialize as a type that *one of a few possibilities.* To do that, it actually tries to serialize as each of the possibilities and expects only one to work. Along the way, it logs about every possibility that fails, even though it *expects* all but one to fail. So this error message is totally normal. It’s not even meaningful as a warning. https://github.com/DataDog/datadog-api-client-typescript/blob/b56725b4ac6154403442ed02fe511c27a960d000/packages/datadog-api-client-v1/models/ObjectSerializer.ts#L2553-L2570
